### ISSUE TITLE
[Infra] 팀원 Device 등록

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/gabbangzip-iOS#21]
## 🚀 Description
- 애플 디벨로퍼 사이트 > Devices (기기)에서 팀원들 실 디바이스 등록 추가

## ✅ TODO
- [x] 애플 디벨로퍼 사이트 > Devices (기기)에서 팀원들 실 디바이스 등록 추가

**Comment by GREENOVER** [comment]
@serena0720 @zekexros 
본인 테스트용으로 사용할 실 디바이스 UDID 공유 부탁드립니다.

저는, 00008030-000978320C2B802E 입니다.

**Comment by serena0720** [comment]
@hope1053 @zekexros 팀원들 테스트할 실기계 UDID 노션에 공유하면 좋을거 같아요~
